export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const OBTENER_PRODUCTOS_EXITO = "OBTENER_PRODUCTOS_EXITO";
export const OBTENER_PRODUCTOS_ERROR = "OBTENER_PRODUCTOS_ERROR";

//----------------- CREAR_EDITAR_ELIMINAR_PRODUCTOS
export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const OBTENER_PRODUCTO_ELIMINAR = "OBTENER_PRODUCTO_ELIMINAR";
export const PRODUCTO_ELIMNADO_EXITO = "PRODUCTO_ELIMNADO_EXITO";
export const PRODUCTO_ELIMNADO_ERROR = "PRODUCTO_ELIMNADO_ERROR";

//OBTENER DATOS PARA EL PANEL ADMINISTRADOR
export const OBTENER_SUBCATEGORIAS = "OBTENER_SUBCATEGORIAS";
export const OBTENER_SUBCATEGORIAS_EXITO = "OBTENER_SUBCATEGORIAS_EXITO";
export const OBTENER_SUBCATEGORIAS_ERROR = "OBTENER_SUBCATEGORIAS_ERROR";

export const NUEVA_SUBCATEGORIA = "NUEVA_SUBCATEGORIA";
export const NUEVA_SUBCATEGORIA_EXITO = "NUEVA_SUBCATEGORIA_EXITO";
export const NUEVA_SUBCATEGORIA_ERROR = "NUEVA_SUBCATEGORIA_ERROR";

export const OBTENER_SUBCATEGORIA_ELIMINAR = "OBTENER_SUBCATEGORIA_ELIMINAR";
export const ELIMINAR_SUBCATEGORIA_EXITO = "ELIMINAR_SUBCATEGORIA_EXITO";
export const ELIMINAR_SUBCATEGORIA_ERROR = "ELIMINAR_SUBCATEGORIA_ERROR";

export const OBTENER_CATEGORIAS = "OBTENER_CATEGORIAS";
export const OBTENER_CATEGORIAS_EXITO = "OBTENER_CATEGORIAS_EXITO";
export const OBTENER_CATEGORIAS_ERROR = "OBTENER_CATEGORIAS_ERROR";

export const OBTENER_MARCAS = "OBTENER_MARCAS";
export const OBTENER_MARCAS_EXITO = "OBTENER_MARCAS_EXITO";
export const OBTENER_MARCAS_ERROR = "OBTENER_MARCAS_ERROR";

export const OBTENER_MARCA = "OBTENER_MARCA";
export const OBTENER_MARCA_EXITO = "OBTENER_MARCA_EXITO";
export const OBTENER_MARCA_ERROR = "OBTENER_MARCA_ERROR";

export const CREAR_MARCA = "CREAR_MARCA";
export const CREAR_MARCA_EXITO = "CREAR_MARCA_EXITO";
export const CREAR_MARCA_ERROR = "CREAR_MARCA_ERROR";

export const EDITAR_MARCA = "EDITAR_MARCA";
export const EDITAR_MARCA_EXITO = "EDITAR_MARCA_EXITO";
export const EDITAR_MARCA_ERROR = "EDITAR_MARCA_ERROR";

export const OBTENER_MARCA_ELIMINAR = "OBTENER_MARCA_ELIMINAR";
export const ELIMINAR_MARCA_EXITO = "ELIMINAR_MARCA_EXITO";
export const ELIMINAR_MARCA_ERROR = "ELIMINAR_MARCA_ERROR";

export const OBTENER_EVENTOS = "OBTENER_EVENTOS";
export const OBTENER_EVENTOS_EXITO = "OBTENER_EVENTOS_EXITO";
export const OBTENER_EVENTOS_ERROR = "OBTENER_EVENTOS_ERROR";

export const AGREGAR_PRODUCTO_EVENTO = "AGREGAR_PRODUCTO_EVENTO";
export const AGREGAR_PRODUCTO_EVENTO_EXITO = "AGREGAR_PRODUCTO_EVENTO_EXITO";
export const AGREGAR_PRODUCTO_EVENTO_ERROR = "AGREGAR_PRODUCTO_EVENTO_ERROR";

export const AGREGAR_EVENTO_PRODUCTO = "AGREGAR_EVENTO_PRODUCTO";
export const AGREGAR_EVENTO_PRODUCTO_EXITO = "AGREGAR_EVENTO_PRODUCTO_EXITO";
export const AGREGAR_EVENTO_PRODUCTO_ERROR = "AGREGAR_EVENTO_PRODUCTO_ERROR";

export const QUITAR_EVENTO_PRODUCTO = "QUITAR_EVENTO_PRODUCTO";
export const QUITAR_EVENTO_PRODUCTO_EXITO = "QUITAR_EVENTO_PRODUCTO_EXITO";
export const QUITAR_EVENTO_PRODUCTO_ERROR = "QUITAR_EVENTO_PRODUCTO_ERROR";

export const ELIMINAR_EVENTO_PRODUCTO = "ELIMINAR_EVENTO_PRODUCTO";
export const ELIMINAR_EVENTO_PRODUCTO_EXITO = "ELIMINAR_EVENTO_PRODUCTO_EXITO";
export const ELIMINAR_EVENTO_PRODUCTO_ERROR = "ELIMINAR_EVENTO_PRODUCTO_ERROR";

export const GUARDAR_EVENTO = "GUARDAR_EVENTO";

//-----------------CLIENTE------------------

export const OBTENER_PRODUCTOS_CLIENTE = "OBTENER_PRODUCTOS_CLIENTE";
export const OBTENER_PRODUCTOS_CLIENTE_EXITO =
  "OBTENER_PRODUCTOS_CLIENTE_EXITO";
export const OBTENER_PRODUCTOS_CLIENTE_ERROR =
  "OBTENER_PRODUCTOS_CLIENTE_ERROR";
